export class DictSklepyDto {
    constructor(
        public idSklep: number = 0,
        public idDictSklepyTyp: number = 0,
        public idDictSklepyRodzaj: number = 0,
        public dictSklepyRodzaj: string = '',
        public idRegion: number = 0,
        public kodSAP: string = '',
        public mpk: string = '',
        public kodPocztowy: string = '',
        public miasto: string = '',
        public ulica: string = '',
        public eMailKierownik: string = '',
        public eMailPracownicy: string = '',
        public eMailProjektanci: string = '',
        public kierownikSklepu: string = '',
        public telefonKierownika: string = '',
        public telefonZCKierownika1: string = '',
        public telefonZCKierownika2: string = '',
        public telefonZCKierownika3: string = '',
        public telefonPracownika1: string = '',
        public telefonPracownika2: string = '',
        public telefonPracownika3: string = '',
        public telefonPracownika4: string = '',
        public telefonPracownika5: string = '',
        public telefonProjektant1: string = '',
        public telefonProjektant2: string = '',
        public telefonProjektant3: string = '',
        public telefonPodstawowy: string = '',
        public telefonStacjonarny: string = '',
        public fax: string = '',
        public aktywny: number = 0
    ){}
}